Fix error after upgrading to Expo SDK 50
Error: Cannot find package '@babel/plugin-proposal-export-namespace-from' imported from ~/expo/examples/with-storybook/babel-virtual-resolve-base.js